STRINGS = {
    "sidebar": {
        "title": "Seitenleiste",
        "provider_select": "Anbieter",
        "model_select": "LLM auswählen",
        "llm_switch": "Analyse per LLM",
        "analyse_teacher_switch": "Lehrkraft analysieren",
        "analyse_students_switch": "Schüler:innen analysieren",
        "prompt_filter_teacher_only": "\n\nWICHTIG: Codiere AUSSCHLIESSLICH Äußerungen der Lehrperson ({teacher_name}). Ignoriere sämtliche Äußerungen der Schüler:innen.",
        "prompt_filter_students_only": "\n\nWICHTIG: Codiere AUSSCHLIESSLICH Äußerungen der Schüler:innen. Ignoriere sämtliche Äußerungen der Lehrperson ({teacher_name}).",
        "prompt_filter_none": "\n\nWICHTIG: Es ist keine Sprechergruppe ausgewählt. Bitte aktiviere in der Seitenleiste mindestens „Lehrkraft analysieren\" oder „Schüler:innen analysieren\".",
        "user_prompt_filter_teacher_only": "\n\nBitte codiere in diesem Transkript AUSSCHLIESSLICH Äußerungen der Lehrperson ({teacher_name}). Überspringe jede Schüler-Äußerung (S01, S02, ...) vollständig.",
        "user_prompt_filter_students_only": "\n\nBitte codiere in diesem Transkript AUSSCHLIESSLICH Schüler-Äußerungen (S01, S02, ...). Überspringe jede Äußerung der Lehrperson ({teacher_name}) vollständig.",
        "user_prompt_filter_none": "\n\nEs ist aktuell keine Sprechergruppe aktiviert — es soll keine Codierung erzeugt werden.",
        "button_analysis": "Analysieren",
        "analysis_completed": "Analyse abgeschlossen",
        "download_report": "Report herunterladen",
        "import_session": "Sitzung importieren",
        "export_session": "Sitzung exportieren",
        "reset_session": "Sitzung zurücksetzen",
        "history_button": "Verlauf",
        "history_title": "Analyse-Verlauf",
        "history_save_now": "Aktuelle Sitzung in den Verlauf speichern",
        "history_load": "Laden",
        "history_delete": "Löschen",
        "history_empty": "Noch keine gespeicherten Sitzungen.",
        "history_select_label": "Gespeicherte Sitzung auswählen",
        "history_col_date": "Datum",
        "history_col_model": "Modell",
        "history_col_group": "Gruppe",
        "history_col_turns": "Beiträge",
        "history_saved_ok": "Im Verlauf gespeichert.",
        "history_loaded_ok": "Sitzung geladen.",
        "history_deleted_ok": "Eintrag gelöscht.",
        "history_save_blocked": "Bitte zuerst eine Analyse durchführen, bevor du sie speicherst.",
        "history_close": "Schließen",
        "tokens_aprox": "Input-Tokens: ca.",
        "cost_prediction": "Geschätzte Mindestkosten",
    },
    "analysis": {
        "tab_title": "Analyse",
        "general_info": "Allgemeine Informationen",
        "group_id": "ID der Gruppe",
        "num_pupils": "Anzahl Schüler:innen", 
        "name_teacher": "Name der Lehrperson im Transkript",
        "name_teacher_var": "LEHRER",
        "document_input": "Dokumenteneingabe",
        "upload_transcript": "Transkript hochladen",
        "upload_codebook": "Codebuch hochladen",
        "preview_codebook": "Vorschau Codebuch",
        "preview_transcript": "Vorschau Transkript",
        "placeholder": "Keine Datei ausgewählt",
        "browse": "Durchsuchen...",
        "placeholder_codebook": "Noch kein Codebuch hochgeladen...",
        "placeholder_transcript": "Noch kein Transkript hochgeladen...",
        "modal_restart_analysis": "Bitte Codebuch hochladen und Analyse erneut starten (ohne LLM)!",
        "modal_title_attention": "Hinweis",
        "modal_reset_session": "Möchten Sie die Sitzung wirklich zurücksetzen? Alle nicht gespeicherten Daten gehen verloren.",
        "modal_title_reset": "Sitzung zurücksetzen",
        "modal_title_error": "Fehler",
        "modal_confirm_reset": "Ja, zurücksetzen!",
        "modal_button_cancel": "Abbrechen",
        "modal_button_close": "Schließen",
        "modal_upload_transcript_first": "Bitte zuerst ein Transkript hochladen!",
        "modal_upload_codebook_first": "Bitte zuerst ein Codebuch hochladen!",
        "teacher_not_found": "Lehrperson nicht im Transkript gefunden.",
        "check_format": "Transkript konvertieren",
        "check_format_tooltip": "Prüft das hochgeladene Transkript auf das erwartete Format (S01, S02, …). Weicht das Format ab (z.B. SPEAKER_00 mit Zeilenumbrüchen innerhalb eines Beitrags), wird eine konvertierte Version erstellt und zum Download angeboten. Die Dateiart (txt, docx) bleibt erhalten.",
        "modal_title_format_check": "Transkript-Formatprüfung",
        "modal_format_already_valid": "Das Transkript liegt bereits im korrekten Format vor.",
        "modal_format_invalid_confirm": "Das Transkript entspricht nicht dem erwarteten Format. Eine konvertierte Version wurde erstellt. Vorschau der ersten Zeilen:",
        "modal_format_pdf_unsupported": "Die Formatkonvertierung wird für PDF-Dateien nicht unterstützt. Bitte laden Sie eine .txt- oder .docx-Datei hoch.",
        "modal_format_docx_table": "Diese .docx-Datei enthält eine Tabelle und kann nicht als Transkript konvertiert werden.",
        "download_converted": "Konvertiertes Transkript herunterladen",
        "format_modal_speakers_title": "Sprecher zuordnen",
        "format_modal_speakers_intro": "Folgende Sprecher wurden im Transkript erkannt. Bitte wählen Sie für jeden, wie er in der konvertierten Datei bezeichnet werden soll.",
        "format_modal_speakers_col_raw": "Erkannter Sprecher",
        "format_modal_speakers_col_target": "Zuordnung",
        "format_speaker_role_teacher": "Lehrperson",
        "format_speaker_role_student_n": "Schüler*in {n}",
        "format_speaker_role_ignore": "Ignorieren",
        "format_modal_brackets_title": "Aktionsbeschreibungen",
        "format_modal_brackets_intro": "Folgende Klammer-Annotationen wurden gefunden. Bitte entscheiden Sie, ob diese behalten oder entfernt werden sollen.",
        "format_bracket_keep": "Behalten",
        "format_bracket_strip": "Entfernen",
        "format_modal_preview_title": "Vorschau",
        "format_modal_button_next": "Weiter",
        "format_modal_button_back": "Zurück",
        "format_modal_button_convert": "Konvertieren",
        "format_modal_no_speakers": "Es konnten keine Sprecher automatisch erkannt werden. Das Transkript kann nicht konvertiert werden.",
        "format_bracket_samples": "Beispiele"
    },
    "results": {
        "tab_title": "Ergebnisse",
        "no_results": "Bitte zuerst eine Analyse durchführen!",
        "no_results_title": "Noch keine Ergebnisse",
        "no_data": "Noch keine Daten vorhanden",
        "section_quantitative_analysis": "Quantitative Verteilung der Gesprächsanteile",
        "class_size": "Klassengröße",
        "num_participants": "Anzahl beteiligter Schüler:innen",
        "participation_rate": "Beteiligungsquote",
        "distribution_of_turns": "Gesprächsverteilung",
        "interaction_turns": "Gesprächsbeiträge",
        "teacher": "Lehrperson",
        "students": "Schüler:innen",
        "turn_count": "Anzahl Beiträge",
        "turn_length": "Länge in Wörtern M (SD)",
        "section_qualitative_analysis": "Qualitative Analyse",
        "impulses_count": "Anzahl der Redezüge",
        "coded_impulses": "Codierte Gesprächsimpulse",
        "most_frequent_codes": "Häufigste Codes",
        "teacher_talking_rate": "Redeanteil (Lehrperson / Schüler:innen)",
        "impulses_distribution": "Verteilung der Gesprächsimpulse",
        "impulses_coding": "Codierung der Gesprächsimpulse",
        "results_group": "Ergebnisse Gruppe",
        "words_total": "Wörter insgesamt",
        "quantity": "Anzahl",
        "speaker": "Sprecher:in",
        "caption": "Legende",
        "section": "Abschnitt",
        "share": "Anteil",
        "section_first": "Erstes Drittel",
        "section_middle": "Mittleres Drittel",
        "section_last": "Letztes Drittel",
        "over_time_quant_title": "Beteiligung im Verlauf",
        "over_time_quali_title": "Code-Verteilung im Verlauf"
    },
    "options": {
        "tab_title": "Optionen",
        "keyring_unavailable": "Kein System-Keyring verfügbar — der API-Schlüssel wird nur für diese Sitzung gespeichert.",
        "api_configuration": "API-Konfiguration",
        "api_select_title": "API-Auswahl",
        "api_select": "OpenAI nutzen",
        "api_groq_found": "API-Key für Groq vorhanden",
        "api_groq_not_found": "Kein API-Key für Groq vorhanden. Bitte konfigurieren.",
        "api_openai_found": "API-Key für openAI vorhanden",
        "api_openai_not_found": "Kein API-Key für openAI vorhanden. Bitte konfigurieren.",
        "api_anthropic_found": "API-Key für Anthropic vorhanden",
        "api_anthropic_not_found": "Kein API-Key für Anthropic vorhanden. Bitte konfigurieren.",
        "api_ollama_found": "Ollama Cloud-API-Key vorhanden",
        "api_ollama_not_found": "Kein Cloud-API-Key — lokales Ollama wird verwendet (localhost)",
        "ollama_running": "Ollama läuft unter {url}",
        "ollama_not_running": "Ollama nicht erreichbar unter {url}",
        "ollama_start_button": "Ollama starten",
        "ollama_start_error": "Ollama konnte nicht gestartet werden. Ist es installiert?",
        "error_title": "Fehler",
        "no_api_key_warning": "Kein API-Key gefunden. Bitte einen API-Key konfigurieren, um LLM-Funktionen zu nutzen.",
        "button_change": "Ändern",
        "add_api_key_placeholder": "API-Key eingeben",
        "add_api_key_save": "Speichern",
        "add_api_key_title": "API-Key ändern",
        "button_delete": "Löschen",
        "delete_api_key_warning": "Möchten Sie den API-Key wirklich löschen?",
        "delete_api_key_confirm": "Ja, löschen!",
        "delete_api_key_title": "API-Key löschen",
        "button_reset": "Zurücksetzen",
        "llm_models": "Modelle für LLM-Auswahl",
        "available_models": "Verfügbare Modelle",
        "add_model": "Modell hinzufügen",
        "button_add": "Hinzufügen",
        "model_id": "Modell-ID",
        "model_provider": "Modell-Anbieter",
        "input_cost": "Kosten pro 1M Input-Tokens (€)",
        "output_cost": "Kosten pro 1M Output-Tokens (€)",
        "cost_placeholder": "z.B., 0.40",
        "add_model_placeholder": "z.B., gpt-4o",
        "modal_button_add": "Hinzufügen",
        "add_model_title": "Ein Modell hinzufügen",
        "remove_model": "Modell entfernen",
        "modal_remove_model_warning": "Möchten Sie die ausgewählten Modelle wirklich entfernen? Dieser Vorgang kann nicht rückgängig gemacht werden.",
        "modal_remove_confirm": "Ja, entfernen!",
        "modal_remove_title": "Modelle entfernen",
        "reset_model_selection_confirm": "Möchten Sie die Modellauswahl wirklich auf den Standard zurücksetzen?",
        "reset_model_selection_title": "Modellauswahl zurücksetzen",
        "modal_model_reset_confirm": "Ja, zurücksetzen!",
        "custom_prompts": "Benutzerdefinierte Prompts",
        "change_system_prompt": "System-Prompt ändern",
        "reset_system_prompt_title": "System-Prompt zurücksetzen",
        "reset_system_prompt_confirm": "Möchten Sie den System-Prompt wirklich zurücksetzen?",
        "change_user_prompt": "User-Prompt ändern",
        "reset_user_prompt_title": "User-Prompt zurücksetzen",
        "reset_user_prompt_confirm": "Möchten Sie den User-Prompt wirklich zurücksetzen?",
        "additional_options": "Weitere Optionen",
        "teacher_name": "Name der Lehrperson",
        "group_id": "ID der Gruppe",
        "num_students": "Anzahl Schüler:innen",
        "reset_group_parameters_title": "Gruppenparameter zurücksetzen",
        "reset_group_parameters_confirm": "Möchten Sie die Gruppenparameter wirklich zurücksetzen?",
        "about": "Über TalkTrace AI",
        "about_text": "TalkTrace AI ist eine Webanwendung zur Analyse von Lehrer-Schüler-Interaktionen in Bildungskontexten. Sie nutzt KI-Sprachmodelle, um sowohl quantitative als auch qualitative Einblicke in Klassendialoge zu bieten, die Lehrkräfte dabei unterstützen, ihre Unterrichtsstrategien zu verbessern und die Schüler:innenbeteiligung zu fördern. Für weitere Informationen besuchen Sie https://github.com/talktrace-ai/talktrace-ai."
    },
    "report": {
        "header": "Gesprächsanalyse – Gruppe",
        "model_used": "Verwendetes LLM-Modell",
        "section_1": "1. Quantitative Verteilung der Gesprächsanteile",
        "class_size": "Klassengröße",
        "pupil_count": "Anzahl beteiligter Schüler:innen",
        "participation_rate": "Beteiligungsquote",
        "table": "Tabelle",
        "interaction_turns_teacher_pupils": "Gesprächsbeiträge der Lehrperson und der Schüler:innen",
        "participants": "Teilnehmende",
        "teacher": "Lehrperson",
        "pupils": "Schüler:innen",
        "quantity": "Anzahl",
        "length_words": "Länge in Wörtern",
        "interaction_turns": "Gesprächsbeiträge",
        "figure": "Abbildung",
        "distribution_of_turns": "Gesprächsverteilung",
        "section_2": "2. Qualitative Codierung der Gesprächsbeiträge",
        "impulses_count": "Anzahl der codierten Beiträge",
        "teacher_impulses": "Codierte sprachliche Beiträge",
        "teacher_statement": "Äußerung (kurz)",
        "speaker": "Sprecher:in",
        "code": "Code",
        "shortcode": "Shortcode",
        "caption": "Legende"
    },
    "system_prompts": {
        "no_code": "Kein Code verwendet",
        "analysis_running": "Die Analyse läuft.",
        "wait": "Dies kann eine Weile dauern...",
        "waiting_LLM": "Warten auf Antwort des LLM...",
        "calculating": "Berechne...",
        "error": "Fehler bei LLM-Analyse",
        "try_again": "Bitte versuchen Sie es erneut!"
    },
    "stats": {
        "students": "Schüler:innen",
        "teacher": "Lehrer:in"
    },
    "testing": {
        "tab_title": "Testen",
        "section_header": "Codebook-Validierung durch Intercoder-Übereinstimmung",
        "intro": "Laden Sie zwei TalkTrace-Reports (.docx, .xlsx oder .html) hoch, die aus demselben Transkript mit unterschiedlichen Modellen erzeugt wurden. Die Impulse werden per Äußerungstext abgeglichen; Cohen's Kappa wird über die zugewiesenen Codes berechnet. Impulse, die nur einer der beiden Reports codiert hat, fließen als Kategorie „unkodiert“ ein.",
        "upload_report_a": "Report A (.docx / .xlsx / .html)",
        "upload_report_b": "Report B (.docx / .xlsx / .html)",
        "placeholder_report": "Noch kein Report hochgeladen...",
        "summary_header": "Überblick",
        "summary_n_pairs": "Abgeglichene Paare",
        "summary_n_both": "Von beiden codiert",
        "summary_only_a": "Nur in A",
        "summary_only_b": "Nur in B",
        "summary_percent_agreement": "Prozentuale Übereinstimmung",
        "summary_krippendorff": "Krippendorff's α",
        "kappa_header": "Cohen's Kappa",
        "kappa_ci_label": "95%-KI",
        "per_code_header": "Übereinstimmung pro Code",
        "per_code_col_code": "Code",
        "per_code_col_n_a": "n (A)",
        "per_code_col_n_b": "n (B)",
        "per_code_col_f1": "F1",
        "per_code_col_precision": "Präzision",
        "per_code_col_recall": "Trefferquote",
        "kappa_not_ready": "Bitte beide Reports hochladen, um Kappa zu berechnen.",
        "kappa_interpretation_poor": "Keine Übereinstimmung",
        "kappa_interpretation_slight": "Geringe Übereinstimmung",
        "kappa_interpretation_fair": "Ausreichende Übereinstimmung",
        "kappa_interpretation_moderate": "Moderate Übereinstimmung",
        "kappa_interpretation_substantial": "Beträchtliche Übereinstimmung",
        "kappa_interpretation_almost_perfect": "Fast perfekte Übereinstimmung",
        "confusion_header": "Code-Konfusionsmatrix (A × B)",
        "confusion_axis_a": "Report A",
        "confusion_axis_b": "Report B",
        "parse_error_no_table": "In der hochgeladenen Datei wurde keine Impuls-Tabelle gefunden. Bitte laden Sie einen TalkTrace-Report (.docx, .xlsx oder .html) hoch.",
        "parse_error_unsupported_format": "Dieses Dateiformat wird nicht unterstützt. Bitte .docx, .xlsx oder .html verwenden.",
        "unmatched_label": "unkodiert",
        "export_report": "Testergebnisse exportieren",
        "export_title": "Intercoder-Übereinstimmung exportieren",
        "export_intro": "Wähle das Ausgabeformat.",
        "no_data": "Keine Testdaten zum Exportieren vorhanden.",
    },
    "report_options": {
        "dialog_title": "Report konfigurieren",
        "dialog_intro": "Wähle aus, welche Abschnitte enthalten sein sollen und in welchem Format.",
        "sections_label": "Inhalte",
        "sec_quant": "Quantitative Verteilung (Tabelle + Plot)",
        "sec_over_time_quant": "Beteiligung im Verlauf (Plot)",
        "sec_quali": "Qualitative Codierung (Plot + Impuls-Tabelle)",
        "sec_over_time_quali": "Code-Verteilung im Verlauf (Plot)",
        "sec_legend": "Code-Legende & Modell-Hinweis",
        "format_label": "Ausgabeformat",
        "format_docx": "DOCX (Word)",
        "format_pdf": "PDF",
        "format_xlsx": "XLSX (Excel)",
        "format_html": "HTML",
        "format_csv": "CSV (ZIP-Bündel)",
        "format_json": "JSON",
        "download_now": "Herunterladen",
        "cancel": "Abbrechen",
        "quali_disabled_hint": "Bitte zuerst die LLM-Analyse durchführen, um qualitative Optionen zu nutzen.",
        "no_section_selected": "Bitte mindestens einen Abschnitt auswählen.",
        "pdf_unavailable": "PDF-Erzeugung fehlgeschlagen (Word oder LibreOffice erforderlich).",
        "pdf_unavailable_linux": "PDF-Export wird unter Linux nicht unterstützt. Bitte stattdessen das DOCX-Format verwenden.",
        "xlsx_unavailable": "Für XLSX wird das Paket openpyxl benötigt.",
        "docx_unavailable": "Für DOCX wird das Paket python-docx benötigt.",
        "sheet_overview": "Übersicht",
        "sheet_quant": "Quant",
        "sheet_quant_over_time": "Verlauf_Quant",
        "sheet_impulses": "Impulse",
        "sheet_quali_over_time": "Verlauf_Quali"
    },
    "onboarding": {
        "demo_button": "Mit Beispieldaten ausprobieren",
        "demo_loaded": "Beispiel geladen — schau dir den Ergebnisse-Tab an.",
        "welcome_title": "Willkommen bei TalkTrace AI",
        "welcome_intro": "In drei Schritten loslegen:",
        "welcome_step_1": "API-Key unter Optionen eintragen (oder Ollama lokal nutzen).",
        "welcome_step_2": "Transkript und Codebuch im Analyse-Tab hochladen.",
        "welcome_step_3": "„Analysieren\" klicken — quantitative Ergebnisse erscheinen sofort, qualitative Codierung sobald das LLM antwortet.",
        "welcome_demo_hint": "Oder klicke auf „Mit Beispieldaten ausprobieren\" und überspringe das Setup.",
        "welcome_close": "Verstanden",
        "welcome_dont_show": "Nicht mehr zeigen",
        "empty_results_message": "Lade im Analyse-Tab ein Transkript und ein Codebuch hoch und klicke auf „Analysieren\".",
        "quickstart_title": "Quick-Start",
        "quickstart_api_key": "API-Key vorhanden",
        "quickstart_model": "Modell ausgewählt",
        "quickstart_transcript": "Transkript hochgeladen",
        "quickstart_codebook": "Codebuch hochgeladen",
        "quickstart_analysis_done": "Analyse durchgeführt",
        "quickstart_status_ok": "Alles bereit",
        "quickstart_status_pending": "Schritte offen",
        "tooltip_group_id": "Freier Bezeichner für diese Diskussion. Wird als Report-Überschrift und Dateinamen-Suffix verwendet.",
        "tooltip_num_pupils": "Gesamtzahl der Schüler:innen in der Klasse. Wird für die Beteiligungsquote (aktive Sprecher:innen / Gesamtzahl) verwendet.",
        "tooltip_name_teacher": "Wie die Lehrperson im Transkript bezeichnet wird (z.B. TEACHER, LEHRER, Frau Müller). Muss exakt zum Transkript passen.",
        "tooltip_upload_transcript": "Plain Text, .docx oder .pdf. Format: ein Beitrag pro Zeile, z.B. „S01: …\". Bei SPEAKER_00-Format „Transkript konvertieren\" nutzen.",
        "tooltip_upload_codebook": "Liste der Codes, die das LLM verwenden darf. Plain Text, .docx oder .pdf. Jeder Code mit Shortcode + kurzer Beschreibung.",
        "tooltip_llm_switch": "Schaltet die qualitative Codierung per LLM ein/aus. Aus = nur quantitative Statistik (kein API-Aufruf, kostenlos).",
        "tooltip_model_select": "Modell für die qualitative Codierung. Größere Modelle kosten mehr, liefern aber bessere Codes."
    }
}
