STRINGS = {
    "sidebar": {
        "title": "Sidebar",
        "provider_select": "Provider",
        "model_select": "Choose a LLM",
        "llm_switch": "LLM Analysis",
        "analyse_teacher_switch": "Analyze teacher",
        "analyse_students_switch": "Analyze students",
        "multi_coding_switch": "Allow multi-coding",
        "prompt_filter_teacher_only": "\n\nIMPORTANT: Code ONLY utterances made by the teacher ({teacher_name}). Ignore all utterances made by students.",
        "prompt_filter_students_only": "\n\nIMPORTANT: Code ONLY utterances made by students. Ignore all utterances made by the teacher ({teacher_name}).",
        "prompt_filter_none": "\n\nIMPORTANT: No speaker group is selected. Please enable at least one of \"Analyze teacher\" or \"Analyze students\" in the sidebar.",
        "user_prompt_filter_teacher_only": "\n\nPlease code ONLY utterances by the teacher ({teacher_name}) in this transcript. Skip every student utterance (S01, S02, ...) entirely.",
        "user_prompt_filter_students_only": "\n\nPlease code ONLY student utterances (S01, S02, ...) in this transcript. Skip every utterance by the teacher ({teacher_name}) entirely.",
        "user_prompt_filter_none": "\n\nNo speaker group is currently enabled — no coding should be produced.",
        "prompt_multi_coding_on": "\n\nIMPORTANT: If multiple codes from the codebook apply to a single utterance, assign ALL of them — emit one separate entry per matching code, with identical 'Sprecher' and 'Impuls' but different 'Shortcode'. Multi-coding utterances is explicitly allowed and encouraged. When an utterance covers multiple distinct aspects or themes (more common in longer utterances), assign one separate code per aspect — length is only an indicator; what matters is thematic diversity. If NO code applies to an utterance, simply omit it — it will appear with an empty Shortcode in the report. Code the ENTIRE transcript to the end; do not stop early.",
        "prompt_multi_coding_off": "\n\nIMPORTANT: Assign AT MOST ONE code from the codebook to each utterance — the most fitting one. If NO code from the codebook applies, omit the utterance from the output (it will appear with an empty Shortcode in the report). Do not multi-code; each utterance appears at most once in the output.",
        "user_prompt_multi_coding_on": "\n\nNote: If multiple codes fit a single utterance, emit each assignment as its own entry (same 'Sprecher' and 'Impuls', different 'Shortcode'). Multi-coding the same utterance is allowed. Pay particular attention to longer utterances: check whether they cover multiple distinct aspects or themes — if so, assign one code per aspect. If no code fits, omit the utterance. Code the transcript completely up to the last utterance — do not terminate the list early.",
        "user_prompt_multi_coding_off": "\n\nNote: Assign AT MOST ONE code per utterance — the most fitting one. If no code applies, omit the utterance. Each utterance appears at most once in the output.",
        "button_analysis": "Analyze",
        "analysis_completed": "Analysis Completed!",
        "download_report": "Download Report",
        "import_session": "Import Session",
        "export_session": "Export Session",
        "reset_session": "Reset Session",
        "history_button": "History",
        "history_title": "Analysis history",
        "history_save_now": "Save current session to history",
        "history_load": "Load",
        "history_delete": "Delete",
        "history_empty": "No saved sessions yet.",
        "history_select_label": "Select a saved session",
        "history_col_date": "Date",
        "history_col_model": "Model",
        "history_col_group": "Group",
        "history_col_turns": "Turns",
        "history_saved_ok": "Saved to history.",
        "history_loaded_ok": "Session loaded.",
        "history_deleted_ok": "Entry deleted.",
        "history_save_blocked": "Run an analysis first before saving to history.",
        "history_close": "Close",
        "cost_prediction": "Minimal Cost Estimation",
        "tokens_aprox": "Input-Tokens: approx.",
    },
    "analysis": {
        "tab_title": "Analysis",
        "general_info": "General Information",
        "group_id": "Group ID",
        "num_pupils": "Number of Students",
        "name_teacher": "Teacher Name in Transcript",
        "name_teacher_var": "TEACHER",
        "document_input": "Document Input",
        "upload_transcript": "Upload Transcript",
        "upload_codebook": "Upload Codebook",
        "preview_codebook": "Codebook Preview",
        "preview_transcript": "Transcript Preview",
        "placeholder": "No file selected",
        "browse": "Browse...",
        "placeholder_codebook": "No codebook uploaded...",
        "placeholder_transcript": "No transcript uploaded...",
        "modal_restart_analysis": "Please upload codebook and restart the analysis (without LLM)!",
        "modal_title_attention": "Attention",
        "modal_reset_session": "Are you sure you want to reset the session? All unsaved data will be lost.",
        "modal_title_reset": "Reset Session",
        "modal_title_error": "Error",
        "modal_confirm_reset": "Yes, reset!",
        "modal_button_cancel": "Cancel",
        "modal_button_close": "Close",
        "modal_upload_transcript_first": "Please upload a transcript first!",
        "modal_upload_codebook_first": "Please upload a codebook first!",
        "teacher_not_found": "Teacher name not found in transcript.",
        "check_format": "Convert transcript",
        "check_format_tooltip": "Checks the uploaded transcript for the expected format (S01, S02, ...). If the format differs (e.g., SPEAKER_00 with line breaks within turns), a converted version is generated and offered for download. The file type (txt, docx) is preserved.",
        "modal_title_format_check": "Transcript Format Check",
        "modal_format_already_valid": "The transcript is already in the correct format.",
        "modal_format_invalid_confirm": "The transcript is not in the expected format. A converted version has been generated. Preview of the first lines:",
        "modal_format_pdf_unsupported": "Format conversion is not supported for PDF files. Please upload a .txt or .docx file.",
        "modal_format_docx_table": "This .docx file contains a table and cannot be converted as a transcript.",
        "download_converted": "Download converted transcript",
        "format_modal_speakers_title": "Map speakers",
        "format_modal_speakers_intro": "The following speakers were detected in the transcript. Choose how each one should be labeled in the converted file.",
        "format_modal_speakers_col_raw": "Detected speaker",
        "format_modal_speakers_col_target": "Mapping",
        "format_speaker_role_teacher": "Teacher",
        "format_speaker_role_student_n": "Student {n}",
        "format_speaker_role_ignore": "Ignore",
        "format_modal_brackets_title": "Action descriptions",
        "format_modal_brackets_intro": "The following bracket-style annotations were detected. Decide whether to keep or remove them.",
        "format_bracket_keep": "Keep",
        "format_bracket_strip": "Remove",
        "format_modal_preview_title": "Preview",
        "format_modal_button_next": "Next",
        "format_modal_button_back": "Back",
        "format_modal_button_convert": "Convert",
        "format_modal_no_speakers": "No speakers could be detected automatically. The transcript cannot be converted.",
        "format_bracket_samples": "Examples"
    },
    "results": {
        "tab_title": "Results",
        "no_results": "Please perform the analysis first!",
        "no_results_title": "No results yet",
        "no_data": "No data available yet",
        "section_quantitative_analysis": "Quantitative Distribution of Conversation Shares",
        "class_size": "Class Size",
        "num_participants": "Number of Participating Students",
        "participation_rate": "Participation Rate",
        "distribution_of_turns": "Distribution of Conversation Turns",
        "interaction_turns": "Conversation Turns",
        "teacher": "Teacher",
        "students": "Students",
        "turn_count": "Number of Turns",
        "turn_length": "Length in Words M (SD)",
        "section_qualitative_analysis": "Qualitative Analysis",
        "impulses_count": "Number of Turns",
        "coded_impulses": "Coded Conversation Impulses",
        "most_frequent_codes": "Most Frequent Codes",
        "teacher_talking_rate": "Talking Share (Teacher / Students)",
        "impulses_distribution": "Distribution of Conversation Impulses",
        "impulses_coding": "Coding of Conversation Impulses",
        "results_group": "Results Group",
        "words_total": "Words Total",
        "quantity": "Quantity",
        "speaker": "Speaker",
        "caption": "Explanation",
        "section": "Section",
        "share": "Share",
        "section_first": "First third",
        "section_middle": "Middle third",
        "section_last": "Last third",
        "over_time_quant_title": "Participation over time",
        "over_time_quali_title": "Code distribution over time"
    },
    "options": {
        "tab_title": "Options",
        "keyring_unavailable": "No system keyring available — the API key will only be kept for this session.",
        "api_configuration": "API Configuration",
        "api_select_title": "API Selection",
        "api_select": "Use OpenAI",
        "api_groq_found": "API key for Groq found",
        "api_groq_not_found": "No API key for Groq found. Please configure.",
        "api_openai_found": "API key for openAI found",
        "api_openai_not_found": "No API key for openAI found. Please configure.",
        "api_anthropic_found": "API key for Anthropic found",
        "api_anthropic_not_found": "No API key for Anthropic found. Please configure.",
        "api_ollama_found": "Ollama cloud API key found",
        "api_ollama_not_found": "No cloud API key — using local Ollama (localhost)",
        "ollama_running": "Ollama is running at {url}",
        "ollama_not_running": "Ollama not reachable at {url}",
        "ollama_start_button": "Start Ollama",
        "ollama_start_error": "Ollama could not be started. Is it installed?",
        "error_title": "Error",
        "no_api_key_warning": "No API key found. Please configure an API key to use LLM features.",
        "button_change": "Change",
        "add_api_key_placeholder": "Enter API key",
        "add_api_key_save": "Save",
        "add_api_key_title": "Change API Key",
        "button_delete": "Delete",
        "delete_api_key_warning": "Are you sure you want to delete the API key?",
        "delete_api_key_confirm": "Yes, delete!",
        "delete_api_key_title": "Delete API Key",
        "button_reset": "Reset",
        "llm_models": "Models for LLM Selection",
        "available_models": "Available Models",
        "add_model": "Add Model",
        "add_model_placeholder": "e.g., gpt-4o",
        "modal_button_add": "Add",
        "add_model_title": "Add a Model",
        "model_id": "Model ID",
        "model_provider": "Model Provider",
        "input_cost": "Cost per 1M Input Tokens (€)",
        "output_cost": "Cost per 1M Output Tokens (€)",
        "cost_placeholder": "e.g., 0.40",
        "remove_model": "Remove Model",
        "modal_remove_model_warning": "Are you sure you want to remove the selected models? This action cannot be undone.",
        "modal_remove_confirm": "Yes, remove!",
        "modal_remove_title": "Remove Models",
        "reset_model_selection_confirm": "Are you sure you want to reset the model selection to default?",
        "reset_model_selection_title": "Reset Model Selection",
        "modal_model_reset_confirm": "Yes, reset!",
        "custom_prompts": "Custom Prompts",
        "change_system_prompt": "Change System Prompt",
        "reset_system_prompt_title": "Reset System Prompt",
        "reset_system_prompt_confirm": "Are you sure you want to reset the system prompt?",
        "change_user_prompt": "Change User Prompt",
        "reset_user_prompt_title": "Reset System Prompt",
        "reset_user_prompt_confirm": "Are you sure you want to reset the system prompt?",
        "additional_options": "Additional Options",
        "teacher_name": "Teacher Name",
        "group_id": "Group ID",
        "num_students": "Number of Students",
        "reset_group_parameters_title": "Reset Group Parameters",
        "reset_group_parameters_confirm": "Are you sure you want to reset the group parameters?",
        "about": "About TalkTrace AI",
        "about_text": "TalkTrace AI is a web application designed for the analysis of teacher-student interactions in educational settings. It leverages advanced language models to provide both quantitative and qualitative insights into classroom dialogues, helping educators enhance their teaching strategies and foster better student engagement. For more info visit https://github.com/talktrace-ai/talktrace-ai."
    },
    "report": {
        "header": "Dialogue analysis – Group",
        "model_used": "LLM model used",
        "section_1": "1. Quantitative Distribution of Conversation Shares",
        "class_size": "Class size",
        "pupil_count": "Number of participating students",
        "participation_rate": "Participation rate",
        "table": "Table",
        "interaction_turns_teacher_pupils": "Conversation turns of teacher and students",
        "participants": "Participants",
        "teacher": "Teacher",
        "pupils": "Students",
        "quantity": "Quantity",
        "length_words": "Length in words",
        "interaction_turns": "Conversation turns",
        "figure": "Figure",
        "distribution_of_turns": "Distribution of turns",
        "section_2": "2. Qualitative Coding of Conversation Turns",
        "impulses_count": "Number of coded turns",
        "teacher_impulses": "Coded verbal turns",
        "teacher_statement": "Statement (short)",
        "speaker": "Speaker",
        "code": "Code",
        "shortcode": "Shortcode",
        "caption": "Legend"
    },
     "system_prompts": {
        "no_code": "No code uses",
        "analysis_running": "Analysis is running.",
        "wait": "This may take a while...",
        "waiting_LLM": "Waiting for LLM response...",
        "calculating": "Calculating...",
        "error": "Error in LLM analysis",
        "try_again": "Please try again."
    },
    "stats": {
        "students": "Students",
        "teacher": "Teacher"
    },
    "testing": {
        "tab_title": "Testing",
        "section_header": "Codebook validation via intercoder agreement",
        "intro": "Upload two TalkTrace reports (.docx, .xlsx, or .html) that were generated from the same transcript with different models. The impulses are aligned by utterance text; Cohen's kappa is computed over the assigned codes. Utterances coded by only one of the two reports contribute as an 'uncoded' category.",
        "upload_report_a": "Report A (.docx / .xlsx / .html)",
        "upload_report_b": "Report B (.docx / .xlsx / .html)",
        "placeholder_report": "No report uploaded...",
        "summary_header": "Overview",
        "summary_n_pairs": "Aligned pairs",
        "summary_n_both": "Coded by both",
        "summary_only_a": "Only in A",
        "summary_only_b": "Only in B",
        "summary_percent_agreement": "Percent agreement",
        "summary_krippendorff": "Krippendorff's α",
        "kappa_header": "Cohen's kappa",
        "kappa_ci_label": "95% CI",
        "per_code_header": "Per-code agreement",
        "per_code_col_code": "Code",
        "per_code_col_n_a": "n (A)",
        "per_code_col_n_b": "n (B)",
        "per_code_col_f1": "F1",
        "per_code_col_precision": "Precision",
        "per_code_col_recall": "Recall",
        "kappa_not_ready": "Please upload both reports to compute kappa.",
        "kappa_interpretation_poor": "Poor agreement",
        "kappa_interpretation_slight": "Slight agreement",
        "kappa_interpretation_fair": "Fair agreement",
        "kappa_interpretation_moderate": "Moderate agreement",
        "kappa_interpretation_substantial": "Substantial agreement",
        "kappa_interpretation_almost_perfect": "Almost perfect agreement",
        "confusion_header": "Code confusion matrix (A x B)",
        "confusion_axis_a": "Report A",
        "confusion_axis_b": "Report B",
        "parse_error_no_table": "Could not find an impulse table in the uploaded file. Please upload a TalkTrace report (.docx, .xlsx or .html).",
        "parse_error_unsupported_format": "This file format is not supported. Please use .docx, .xlsx or .html.",
        "unmatched_label": "uncoded",
        "export_report": "Export testing results",
        "export_title": "Export intercoder agreement",
        "export_intro": "Select the output format.",
        "no_data": "No testing data available to export.",
    },
    "report_options": {
        "dialog_title": "Configure report",
        "dialog_intro": "Select which sections to include and the output format.",
        "sections_label": "Content",
        "sec_quant": "Quantitative distribution (table + plot)",
        "sec_over_time_quant": "Participation over time (plot)",
        "sec_quali": "Qualitative coding (plot + impulses table)",
        "sec_over_time_quali": "Code distribution over time (plot)",
        "sec_legend": "Code legend & model info",
        "format_label": "Output format",
        "format_docx": "DOCX (Word)",
        "format_pdf": "PDF",
        "format_xlsx": "XLSX (Excel)",
        "format_html": "HTML",
        "format_csv": "CSV (ZIP bundle)",
        "format_json": "JSON",
        "download_now": "Download",
        "cancel": "Cancel",
        "quali_disabled_hint": "Run LLM analysis first to enable qualitative options.",
        "no_section_selected": "Please select at least one section.",
        "pdf_unavailable": "PDF generation failed (Word or LibreOffice required).",
        "pdf_unavailable_linux": "PDF export is not supported on Linux. Please use the DOCX format instead.",
        "xlsx_unavailable": "XLSX generation requires the openpyxl package.",
        "docx_unavailable": "DOCX generation requires the python-docx package.",
        "sheet_overview": "Overview",
        "sheet_quant": "Quant",
        "sheet_quant_over_time": "Quant_over_time",
        "sheet_impulses": "Impulses",
        "sheet_quali_over_time": "Quali_over_time"
    },
    "onboarding": {
        "demo_button": "Try with example data",
        "demo_loaded": "Example loaded — explore the Results tab.",
        "welcome_title": "Welcome to TalkTrace AI",
        "welcome_intro": "Three quick steps to get started:",
        "welcome_step_1": "Add an API key under Options (or use Ollama locally).",
        "welcome_step_2": "Upload a transcript and a codebook in the Analysis tab.",
        "welcome_step_3": "Click \"Analyze\" — quantitative results appear immediately, qualitative coding once the LLM responds.",
        "welcome_demo_hint": "Or click \"Try with example data\" to skip setup and explore.",
        "welcome_close": "Got it",
        "welcome_dont_show": "Don't show again",
        "empty_results_message": "Upload a transcript and a codebook in the Analysis tab and click \"Analyze\".",
        "quickstart_title": "Quick start",
        "quickstart_api_key": "API key configured",
        "quickstart_model": "Model selected",
        "quickstart_transcript": "Transcript uploaded",
        "quickstart_codebook": "Codebook uploaded",
        "quickstart_analysis_done": "Analysis complete",
        "quickstart_status_ok": "Ready",
        "quickstart_status_pending": "Steps left",
        "tooltip_group_id": "Free-form label for this discussion. Used as report header and filename suffix.",
        "tooltip_num_pupils": "Total students in the class. Used to compute the participation rate (active speakers / total).",
        "tooltip_name_teacher": "How the teacher is labeled in the transcript (e.g. TEACHER, LEHRER, Frau Müller). Must match the transcript exactly.",
        "tooltip_upload_transcript": "Plain text, .docx or .pdf. Format: one turn per line, e.g. \"S01: ...\". Use \"Convert transcript\" if your file uses SPEAKER_00 headers.",
        "tooltip_upload_codebook": "List of codes the LLM may use. Plain text, .docx or .pdf. Each code with shortcode + brief description.",
        "tooltip_llm_switch": "Toggles qualitative coding via LLM. Off = quantitative stats only (no API call, free).",
        "tooltip_model_select": "Model used for qualitative coding. Larger models cost more but produce better codes."
    }
}
